---
title: "Licitaciones 2014"
author: "DCC Grupo de Licitaciones"
date: "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
output:
  html_document:
    theme: spacelab
    toc: yes
    toc_float:
      collapsed: no
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(visdat)
library(lattice)
library(GGally)
library(tidyverse)
library(kableExtra)
```

### Ingesta de Datos

```{r}
licitaciones <- feather::read_feather("licitaciones.feather")
summary(licitaciones)
head(licitaciones)
```

# Análisis exploratorio

### Revision de N/A

```{r, cache=TRUE}
vis_miss(licitaciones)
sapply(licitaciones, function(x) sum(is.na(x)))
```

Basados en el gráfico podemos concluir que la variable `fecha_de_adjudicacion` no es relevante para el análisis ya que todos sus valores son nulos.


### Remover columnas

```{r}
licitaciones <- licitaciones %>%
  select(- fecha_de_adjudicacion) %>%
  drop_na()
```


### Representacion de los datos

```{r}
ggplot(data=licitaciones, aes(x=ano)) +
  geom_bar() +
  facet_wrap(~licitaciones$monedda) +
  scale_fill_viridis_d() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  # theme_bw() +
  ggtitle("Cantidad de licitaciones por año y por moneda")
```

### Instituciones con mayor cantidad de adjudicaciones en colones
```{r, eval = TRUE, cache = TRUE,  message = FALSE, warning = FALSE}
licitaciones %>%
  group_by(institucion) %>%
  summarise(
    total = n()
  ) %>%
  arrange(desc(total)) %>%
  slice(1:30) %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r}
cantidad_proveedor <- licitaciones %>%
  group_by(proveedor_adjudicado) %>%
  summarise(
    total = n()
  ) %>%
  slice(1:30) %>%
  arrange(desc(total))

kable(cantidad_proveedor) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r}
ggplot(cantidad_proveedor, 
              aes(x = proveedor_adjudicado, y = total, color = proveedor_adjudicado, fill = proveedor_adjudicado, label = total)) +
    geom_col() +
    geom_text(nudge_y = -1, color = "black",size=2, angle=25) + 
    ggtitle("Cantidad de adjudicaciones por proveedor") + 
    xlab("Proveedor") + ylab("Cantidad") +
    theme_bw() + theme(legend.position = "none") + 
    theme(plot.title = element_text(hjust = 0.5,
                                    size=rel(2), #Tamaño relativo de la letra del título
                                    family="Comic Sans MS",
                                    vjust=2, #Justificación vertical, para separarlo del gráfico
                                    face="bold", #Letra negrilla. Otras posibilidades "plain", "italic", "bold" y "bold.italic"
                                    color="blue", #Color del texto
                                  lineheight=1.5))

```